name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[17.2.0, 17.4.0)'
    
    - name: Restore packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /t:Restore Dota2CachePatcher.sln

    - name: Run BeforeBuild explicitly
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /t:BeforeBuild ./Dota2CachePatcher/Dota2CachePatcher.csproj

    - name: Run Protobuf_Compile explicitly
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /t:Protobuf_Compile ./Dota2CachePatcher/Dota2CachePatcher.csproj
    
    - name: Build solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} Dota2CachePatcher.sln
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Dota2CachePatcher
        path: ${{env.GITHUB_WORKSPACE}}/Dota2CachePatcher/bin/Release
  
